# Generated by Django 4.1.7 on 2023-03-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(max_length=100)),
                ('about_region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('active', 'Активний відпочинок'), ('eat', 'Їжа та напої'), ('nature', 'Природа та ландшафти'), ('panoramic', 'Панорамні види'), ('areas', 'Площа'), ('hotels', 'Готелі та місця для проживання'), ('museums', 'Музеї та виставки'), ('church', 'Церкви та місця релігійного значення'), ('sights', "Достопримічальності та пам'ятки"), ('other', 'Інше'), ('forgotten_place', 'Забуті місця')], max_length=20)),
                ('about', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='location_photos/')),
                ('address', models.CharField(max_length=200)),
                ('map_link', models.URLField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
        ),
    ]
