# Generated by Django 4.1.7 on 2023-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='route',
            field=models.TextField(default='*'),
            preserve_default=False,
        ),
    ]
