# Generated by Django 4.1.7 on 2023-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cost',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Активний відпочинок', 'Активний відпочинок'), ('Їжа та напої', 'Їжа та напої'), ('Природа та ландшафти', 'Природа та ландшафти'), ('Панорамні види', 'Панорамні види'), ('Площа', 'Площа'), ('Готелі та місця для проживання', 'Готелі та місця для проживання'), ('Музеї та виставки', 'Музеї та виставки'), ('Церкви та місця релігійного значення', 'Церкви та місця релігійного значення'), ("Достопримічальності та пам'ятки", "Достопримічальності та пам'ятки"), ('Інше', 'Інше'), ('Забуті місця', 'Забуті місця')], max_length=50),
        ),
    ]
